services:
  - type: web
    name: r8-pocketbase
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /api/health 